services:
  db:
    image: mysql:8.4
    container_name: skn36-2team-db

    environment:
      MYSQL_ROOT_PASSWORD: root1234

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro

volumes:
  mysql_data: