"""Export only reference-data tables to database/02_seed.sql."""

from __future__ import annotations

from datetime import date, datetime
from pathlib import Path

from load_data import ROOT, connect


OUTPUT = ROOT / "database" / "02_seed.sql"
TABLES = [
    ("region", ["region_id", "region_name", "area_km2"], "region_id"),
    ("date", ["date_ym", "date_half", "date_quarter", "date_year", "date_month"], "date_ym"),
    ("category", ["category_id", "category_main", "category_sub"], "category_id"),
    ("people", ["region_id", "date_ym", "people_population"], "region_id, date_ym"),
    ("vehicle", ["category_id", "region_id", "date_ym", "vehicle_count"], "category_id, region_id, date_ym"),
]
BATCH_SIZE = 1_000


def sql_value(connection, value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (date, datetime)):
        return f"'{value:%Y-%m-%d}'"
    if isinstance(value, (int, float)):
        return str(value)
    return connection.escape(value)


def main() -> None:
    connection = connect()
    lines = [
        "-- Generated by etl/export_seed.py; reference data only.",
        "USE logistics_db;",
        "SET NAMES utf8mb4;", "SET FOREIGN_KEY_CHECKS=0;", "START TRANSACTION;",
        "DELETE FROM vehicle;", "DELETE FROM people;", "DELETE FROM category;",
        "DELETE FROM `date`;", "DELETE FROM region;", "",
    ]
    counts = {}
    try:
        with connection.cursor() as cursor:
            for table, columns, order_by in TABLES:
                quoted_table = f"`{table}`"
                cursor.execute(f"SELECT {', '.join(f'`{c}`' for c in columns)} FROM {quoted_table} ORDER BY {order_by}")
                count = 0
                while rows := cursor.fetchmany(BATCH_SIZE):
                    values = ["(" + ",".join(sql_value(connection, value) for value in row) + ")" for row in rows]
                    lines.append(f"INSERT INTO {quoted_table} ({', '.join(f'`{c}`' for c in columns)}) VALUES\n" + ",\n".join(values) + ";")
                    count += len(rows)
                counts[table] = count
                lines.append("")
        lines.extend(["COMMIT;", "SET FOREIGN_KEY_CHECKS=1;", ""])
        OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    finally:
        connection.close()
    print(f"생성 완료: {OUTPUT}")
    for table, count in counts.items():
        print(f"{table}: {count:,} rows")


if __name__ == "__main__":
    main()
